# Generated by Django 4.2.7 on 2024-10-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_end_date_alter_task_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='subs',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
