# Generated by Django 5.1.2 on 2024-10-26 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_turma_task_turma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='turma',
        ),
        migrations.DeleteModel(
            name='Turma',
        ),
    ]
