# Generated by Django 4.2.7 on 2024-10-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_subs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='subs',
            field=models.TextField(default=0),
        ),
    ]
