# Generated by Django 5.1.2 on 2024-12-01 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_turma_nome'),
        ('tasks', '0004_remove_task_subs_remove_task_total_subs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_set', to='classes.turma'),
        ),
    ]
