# Generated by Django 4.2.7 on 2024-10-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_subs'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='total_subs',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
